# 00.PyThorch Fundamentals

Resource notebook: https://www.learnpytorch.io/00_pytorch_fundamentals/

In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.0.0+cu118


##Introduction to Tensors

###Creating tensors
###PyTorch tensors are created using torch.Tensor() = https://pytorch.org/docs/stable/tensors.html

### Scalar, Vectors, Matrix, Tensors

In [ ]:
# Scalar --> create tensor
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
# Get tensor back as Python int
scalar.item()

7

In [ ]:
# Vector
vector = torch.tensor ([7,7])
vector

tensor([7, 7])

In [ ]:
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
#Matrix
MATRIX = torch.tensor([[7,8],
                      [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX[0]

tensor([7, 8])

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
#TENSOR
TENSOR = torch.tensor([[[1,2,3],
                       [3,4,5],
                       [2,4,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 4, 5],
         [2, 4, 5]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([1, 3, 3])

In [ ]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 4, 5],
        [2, 4, 5]])

In [ ]:
TENSOR[0,2,1]

tensor(4)

### Random tensors

In [ ]:
# Create a random tensor of size (3, 4)     https://pytorch.org/docs/stable/generated/torch.rand.html
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.3429, 0.4916, 0.2333, 0.0493],
        [0.7081, 0.3822, 0.9136, 0.1243],
        [0.3336, 0.5227, 0.7058, 0.2970]])

In [ ]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(3, 224, 224))
#size=(height, width, number of color channels (R,G,B))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

### Zeros and ones

In [ ]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
zeros*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
#create a tensor of all ones
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
ones.dtype

torch.float32

In [ ]:
ones*random_tensor

tensor([[0.3429, 0.4916, 0.2333, 0.0493],
        [0.7081, 0.3822, 0.9136, 0.1243],
        [0.3336, 0.5227, 0.7058, 0.2970]])

### Creating a range of tensors and tensors-like

In [ ]:
# Use torch.range()
one_to_ten = torch.arange(start=1, end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
# Creating tensors like
ten_zeros = torch.zeros_like(one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

**Note:** Tensor datatypes is one of the 3 big errors you'll run into PyTorch & DL:
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

Precision in computing - https://en.wikipedia.org/wiki/Precision_(computer_science)

In [ ]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None,    # what datatype is the tensor (e.g. float32 or float16)
                               device=None,   # what device is your tensor on (e.g. CPU, Cuda, GPU)
                               requires_grad=False) # whether or not to track gradients with this tensors operations
float_32_tensor

tensor([3., 6., 9.])

In [ ]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor.dtype

torch.float16

In [ ]:
float_32_tensor = float_16_tensor.type(torch.float32)
float_32_tensor.dtype
float_32_tensor

tensor([3., 6., 9.])

In [ ]:
#verificare se la molt. funziona anche con tipo di dati diversi. Funziona
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [ ]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [ ]:
#verificare se la molt. funziona anche con tipo di dati diversi. Funziona
int_32_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [ ]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.long)
int_32_tensor

tensor([3, 6, 9])

In [ ]:
#verificare se la molt. funziona anche con tipo di dati diversi. Funziona
int_32_tensor * float_32_tensor

tensor([ 9., 36., 81.])

### Getting information from tensors (tensor attributes)

1. Tensors not right datatype - to do get datatype from a tensor, can use 'tensor.dtype'
2. Tensors not right shape - to get shape from a tensor, can use 'tensor.shape'
3. Tensors not on the right device - to get device from a tensor (cpu o gpu), can use 'tensor.device'

In [ ]:
#Create a tensor
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.2545, 0.4322, 0.4294, 0.2699],
        [0.1559, 0.8530, 0.5105, 0.0151],
        [0.4144, 0.6928, 0.1446, 0.0971]])

In [ ]:
#Find out details about some tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")  #.size, .shape uguali (shape è un attributo, size è un metodo)
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.2545, 0.4322, 0.4294, 0.2699],
        [0.1559, 0.8530, 0.5105, 0.0151],
        [0.4144, 0.6928, 0.1446, 0.0971]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


### Manipulatting Tensors (tensor operations)

Tensor operations include:
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix multiplication

In [ ]:
# Create a tensor and addition
tensor = torch.tensor([1, 2, 3])
tensor = tensor + 10

In [ ]:
# Multiply tensor by 10
tensor = tensor * 10
tensor

tensor([110, 120, 130])

In [ ]:
# Substraction
tensor = tensor -20
tensor

tensor([ 90, 100, 110])

In [ ]:
# Try out PyTorch in-built function
torch.mul(tensor, 10)
torch.add(tensor, 20)

tensor([110, 120, 130])

### Matrix multiplication

two main ways of performing mulpliplication in neural networks and DL:
* Element-wise mulplication
* Matrix mulplication (dot product)


In [ ]:
# Element wise multiplication
print(tensor, "*", tensor)
print(f"Equals: {tensor * tensor}")

tensor([ 90, 100, 110]) * tensor([ 90, 100, 110])
Equals: tensor([ 8100, 10000, 12100])


In [ ]:
# Matrix multiplication vettore * vettore = numero (riga*colonna)
%%time    #Per vedere quanto ci impiega
torch.matmul(tensor, tensor)

CPU times: user 421 µs, sys: 32 µs, total: 453 µs
Wall time: 461 µs


tensor(30200)

In [ ]:
#Altro modo per fare una moltiplicazione di matrici
tensor @ tensor

tensor(30200)

There are two rules that performing matrix multiplication needs to satisfy:
1. The **inner dimensions** must match:
* '(3, 2) @ (3, 2)' won't work
* '(3, 2) @ (2,3)' will work
* '(2, 3) @ (3,2)' will work

2. The resulting matrix has the shape of the **outer dimensios**:
* '(2,3) @ (3,2)' -> '(2, 2)'
* '(3, 2) @ (2, 3)' -> '(3, 3)'


Esempi ed esercizi: http://matrixmultiplication.xyz/

In [ ]:
# Errore il più comune in DL
torch.matmul(torch.rand(3,2), torch.rand(3,2))

RuntimeError: ignored

In [ ]:
#Corretto

torch.matmul(torch.rand(2,3), torch.rand(3,2))

tensor([[0.8350, 0.7048],
        [0.2627, 0.2083]])

In [ ]:
#Corretto e con una dimensione dell'output diversa (2)
torch.matmul(torch.rand(3,2), torch.rand(2,3))

tensor([[0.3160, 0.3807, 0.1098],
        [0.4772, 0.6776, 0.3007],
        [0.2150, 0.3381, 0.1786]])

### One of the most common errors in DL: shape errors

In [ ]:
# Shapes for matrix multiplication
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])
tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]])
#torch.mm(tensor_A, tensor_B) #.mm is the same of .matmul (its for writing less code)
torch.matmul(tensor_A, tensor_B)

RuntimeError: ignored

In [ ]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

To fix our tensor shape issues, we can manipulate the shape of one of our tensors using:
A **transpose** switches the axes or dimensions of a given tensor

In [ ]:
tensor_B, tensor_B.shape

(tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]),
 torch.Size([3, 2]))

In [ ]:
#è la trasposta
tensor_B.T, tensor_B.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [ ]:
# The matrix mulpiplication operation works when tensor_B is transposed
print(f"Original shapes: tensorA = {tensor_A.shape} tensorB = {tensor_B.shape}")
print(f"New shapes: tensorA = {tensor_A.shape} tensorB.T = {tensor_B.T.shape}")
print(f"Multiplying: {tensor_A.shape} @ {tensor_B.T.shape} <- inner dimensions must match")
output = torch.matmul(tensor_A, tensor_B.T)
print(output)
#Ora è corretto
print(f"\nOutput shape: {output.shape}")

Original shapes: tensorA = torch.Size([3, 2]) tensorB = torch.Size([3, 2])
New shapes: tensorA = torch.Size([3, 2]) tensorB.T = torch.Size([2, 3])
Multiplying: torch.Size([3, 2]) @ torch.Size([2, 3]) <- inner dimensions must match
tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

Output shape: torch.Size([3, 3])


## Finding the min, max, mean, sum, etc (tensor aggregation)

In [ ]:
# Create a tensor
x = torch.arange(2, 100, 10)
x

tensor([ 2, 12, 22, 32, 42, 52, 62, 72, 82, 92])

In [ ]:
# Find the min
torch.min(x), x.min()

(tensor(0), tensor(0))

In [ ]:
# Find the max
torch.max(x), x.max()

(tensor(90), tensor(90))

In [ ]:
# Find the mean (media)
torch.mean(x), x.mean
#errore con il tipo di dato

RuntimeError: ignored

In [ ]:
# Mean function can't work on tensors with data type long
x.dtype

torch.int64

In [ ]:
# Find the mean (media) - note: the torch.mean() function requires a tensor of float32 datatype
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean

(tensor(45.), <function Tensor.mean>)

In [ ]:
# Find the sum
x.sum(), torch.sum(x)

(tensor(450), tensor(450))

## Finding the positional min and max

In [ ]:
# Find the position in tensor that ha the minimal value with argmin() -> return index position of target tensor where the minimum value occurs 
x.argmin()

tensor(0)

In [ ]:
# Find the position in tensor that has the maximum value with argmax()
x.argmax()

tensor(9)

## Reshaping, stacking, squeezing and unsqueezing tensors

* Reshaping - reshapes an input tensor to a defined shape
* View - return a view of an input tensor of certain shape but keep the same memory as the original tensor
*Stacking - combine multiple tensors on top of each other (vstack) or side by side (hstack)
* Squeeze - removes all '1' dimensions from a tensor
* Unsqueeze - add a '1' dimension to a target tensor
* permute - return a view of the input with dimensions permuted (swapped) in a certain way.

In [ ]:
# Let's create a tensor
import torch
x= torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [ ]:
# Add an extra dimension
x_reshaped = x.reshape(1, 7)
#Not correct!
x_reshaped, x_reshaped.shape

RuntimeError: ignored

In [ ]:
# Add an extra dimension
x_reshaped = x.reshape(1, 9)
# Correct
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
# Add an extra dimension
x_reshaped = x.reshape(9, 1)
# Correct
x_reshaped, x_reshaped.shape

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [ ]:
# CHange the view
z = x.view(1, 9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
# Changing z changes x (because a view of a tensor shares the same memory as the original input)
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [ ]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [ ]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=1)
x_stacked

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [ ]:
# torch.squeeze() - removes all single dimensions from a target tensor
x_reshaped, x_reshaped.shape

(tensor([[5.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [ ]:
# Remove extra dimensions from X_reshaped
#toglie una dimensione, infatti c'è un solo paio di parentesi quadre
x_squeezed = x_reshaped.squeeze()
x_squeezed, x_reshaped.squeeze().shape

(tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [ ]:
# torch.unsqueeze() - adds a single dimension to a target tensor at a specific dim
print(f"Previous target: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

# Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"\nNew shape: {x_unsqueezed.shape}")

# Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=1)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"\nNew shape: {x_unsqueezed.shape}")

Previous target: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([9])

New tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])

New shape: torch.Size([1, 9])

New tensor: tensor([[5.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])

New shape: torch.Size([9, 1])


In [ ]:
# torch.permute - rearranges the dimensions of a target tensor in a specified order
x_original = torch.rand(size=(224, 224, 3)) # [height, width, color_channels]

# Permute the original tensor to rearrange the axis (or dim) order
x_permuted = x_original.permute(2, 0, 1) # shifts axis 0->1, 1->2, 2->0

print(f"Previous target: {x_original}")
print(f"\nPrevious shape: {x_original.shape}")
print(f"\nNew target permuted: {x_permuted}")
print(f"\nNew shape permuted: {x_permuted.shape}")  #[clour_channels, height, width]

Previous target: tensor([[[0.9455, 0.2123, 0.7479],
         [0.1511, 0.3362, 0.8181],
         [0.2629, 0.4750, 0.2257],
         ...,
         [0.1245, 0.9682, 0.9825],
         [0.8460, 0.4254, 0.2718],
         [0.0617, 0.3614, 0.2731]],

        [[0.5958, 0.6252, 0.8524],
         [0.6335, 0.2467, 0.6067],
         [0.1424, 0.0070, 0.0093],
         ...,
         [0.7331, 0.8868, 0.2131],
         [0.9048, 0.0952, 0.2871],
         [0.2535, 0.6136, 0.8906]],

        [[0.4397, 0.8903, 0.0298],
         [0.6454, 0.2981, 0.5459],
         [0.7107, 0.4030, 0.2348],
         ...,
         [0.2564, 0.4959, 0.6929],
         [0.3552, 0.4044, 0.9558],
         [0.0290, 0.7809, 0.3000]],

        ...,

        [[0.0523, 0.0506, 0.7337],
         [0.5641, 0.5850, 0.4982],
         [0.9657, 0.9612, 0.5434],
         ...,
         [0.5286, 0.5666, 0.8850],
         [0.4039, 0.4939, 0.7297],
         [0.9264, 0.4875, 0.0855]],

        [[0.6326, 0.7406, 0.9196],
         [0.1066, 0.1451, 0.69

In [ ]:
# Cabiare un solo valore
x_original[0,1,1] = 99999
x_original

tensor([[[1.1100e+02, 1.1100e+02, 7.4786e-01],
         [1.5110e-01, 9.9999e+04, 8.1815e-01],
         [2.6292e-01, 4.7504e-01, 2.2572e-01],
         ...,
         [1.2449e-01, 9.6822e-01, 9.8250e-01],
         [8.4600e-01, 4.2540e-01, 2.7184e-01],
         [6.1684e-02, 3.6139e-01, 2.7315e-01]],

        [[1.1100e+02, 6.2520e-01, 8.5239e-01],
         [6.3351e-01, 1.1100e+02, 6.0667e-01],
         [1.4242e-01, 6.9981e-03, 9.2739e-03],
         ...,
         [7.3309e-01, 8.8684e-01, 2.1307e-01],
         [9.0476e-01, 9.5183e-02, 2.8713e-01],
         [2.5345e-01, 6.1361e-01, 8.9063e-01]],

        [[4.3971e-01, 8.9035e-01, 2.9811e-02],
         [6.4541e-01, 2.9813e-01, 5.4591e-01],
         [7.1072e-01, 4.0303e-01, 2.3478e-01],
         ...,
         [2.5641e-01, 4.9592e-01, 6.9289e-01],
         [3.5524e-01, 4.0442e-01, 9.5578e-01],
         [2.9000e-02, 7.8094e-01, 2.9995e-01]],

        ...,

        [[5.2288e-02, 5.0623e-02, 7.3374e-01],
         [5.6412e-01, 5.8502e-01, 4.9816e-01]

In [ ]:
# Vedere, dopo aver fatto il permuted dov'è andato
x_permuted = x_original.permute(2, 0, 1)
x_permuted

tensor([[[1.1100e+02, 1.5110e-01, 2.6292e-01,  ..., 1.2449e-01,
          8.4600e-01, 6.1684e-02],
         [1.1100e+02, 6.3351e-01, 1.4242e-01,  ..., 7.3309e-01,
          9.0476e-01, 2.5345e-01],
         [4.3971e-01, 6.4541e-01, 7.1072e-01,  ..., 2.5641e-01,
          3.5524e-01, 2.9000e-02],
         ...,
         [5.2288e-02, 5.6412e-01, 9.6565e-01,  ..., 5.2864e-01,
          4.0390e-01, 9.2641e-01],
         [6.3258e-01, 1.0662e-01, 7.4872e-01,  ..., 9.8571e-01,
          1.8501e-01, 3.8697e-01],
         [5.8417e-01, 3.3526e-01, 7.9950e-01,  ..., 8.2577e-02,
          5.5068e-01, 5.4634e-01]],

        [[1.1100e+02, 9.9999e+04, 4.7504e-01,  ..., 9.6822e-01,
          4.2540e-01, 3.6139e-01],
         [6.2520e-01, 1.1100e+02, 6.9981e-03,  ..., 8.8684e-01,
          9.5183e-02, 6.1361e-01],
         [8.9035e-01, 2.9813e-01, 4.0303e-01,  ..., 4.9592e-01,
          4.0442e-01, 7.8094e-01],
         ...,
         [5.0623e-02, 5.8502e-01, 9.6124e-01,  ..., 5.6663e-01,
          4.939

## Indexing (selecting data from tensors)

Indexing with pytorch is similar to indexing with numpy

In [ ]:
# Create a tensor
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [ ]:
# Let's index on our new tensor
x[0]

tensor([4, 5, 6])

In [ ]:
# Let's index on the middle braket (dim=1)
x[0,1], x[0] [1]

(tensor([4, 5, 6]), tensor([4, 5, 6]))

In [ ]:
# Let's index on the most inner bracket (last dimension)
x[0,1,2], x[0] [1] [2]

(tensor(6), tensor(6))

In [ ]:
# Errore fuori dalla dimensione
x[1] [1] [2]

IndexError: ignored

In [ ]:
# you can also use ":" to select "all" of a target dimension
x[:, 0, :], x[:, 1, 1]

(tensor([[1, 2, 3]]), tensor([5]))

In [ ]:
# Get all values of 0th and 1st dimensions but only index 1 of 2nd dimension
x[:, :, 1]

tensor([[2, 5, 8]])

In [ ]:
x[:, 2, 2], x[:, :, 2]

(tensor([9]), tensor([[3, 6, 9]]))

## PyTorch tensors & NumPy

NumPy in a popular scientifical Python numerical computing library.

And because of this, PyTorch has functionality to interact with it.

* Data in NumPy, wnat in PyTorch tensor -> 'torch.from_numpy(ndarray)'
* PyTorch tensor -> NumPy -> torch.Tensor.numpy()


In [ ]:
# NumPy array to tensor
import torch
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)  #warning: when converting from numpy to pytorch, pytorch reflects numpy's default datattype of  float 64 unless specified otherwise
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [ ]:
# Change the value of array, what will this do to 'tensor'
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [ ]:
# Tensor to NumPy array
tensore = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 2., 3., 4., 5., 6., 7.]),
 array([1., 2., 3., 4., 5., 6., 7.], dtype=float32))

## Reproducibility (trying to take random out of random)

In short how a neural network learns:

'start with random numbers -> tensor operations -> update random numbers to try and them better representations of the data -> again -> again...

To reduce the randomness in neural networks and pyTorch comes the concept of a **random seed**

Essentially what the random seed does is "flavour" the randomness

link:
* https://pytorch.org/docs/stable/notes/randomness.html
* https://en.wikipedia.org/wiki/Random_seed

In [ ]:
import torch

# Create two random tensors
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.3808, 0.7802, 0.1795, 0.5085],
        [0.8472, 0.6178, 0.5145, 0.4539],
        [0.6376, 0.7045, 0.7009, 0.4954]])
tensor([[0.3727, 0.0196, 0.4068, 0.5019],
        [0.8886, 0.9230, 0.5982, 0.8191],
        [0.4753, 0.7673, 0.3081, 0.0067]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [ ]:
# Let's make some random but reproducible tensors

# Set the random seed (Seed = seme)
RANDOM_SEED = 42
#Non corretto
torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3, 4)

random_tensor_D = torch.rand(3, 4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8694, 0.5677, 0.7411, 0.4294],
        [0.8854, 0.5739, 0.2666, 0.6274],
        [0.2696, 0.4414, 0.2969, 0.8317]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [ ]:
# Let's make some random but reproducible tensors

# Set the random seed (Seed = seme)
RANDOM_SEED = 42
#Corretto
torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3, 4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3, 4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

## Running tensors and PyTorch object on the GPUs

GPUs = faster computation on numbers, thanks to CUDA + NVIDIA hardware + PyTorch working behind the scenes to make everything hunky dory (good).

### 1. Getting a GPU

1. Easiest - Use Google Colab for a free GPU (options to upgrade as well)
2. Use your own GPU - takes a little bit of setup and requires the investment of purchasing a GPU, there's lots of options...
https://pytorch.org/get-started/locally/
3. Use cloud computing

For 2, 3 PyTorch + GPU drivers (CUDA) takes a little bit of setting up, to do this, refer to PyTorch setup documentation

In [ ]:
!nvidia-smi

Thu Apr 13 19:16:15 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.85.12    Driver Version: 525.85.12    CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   40C    P8     9W /  70W |      0MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

### 2. Check for GPU access with PyTorch

In [ ]:
# Check for GPU access with PyTorch
torch.cuda.is_available()

True

For PyTorch since it's capable of running compute on the GPU or CPU, it's best practice to setup device agnotisc code.

E.G. run on GPU if available, else default to CPU

In [ ]:
# Setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [ ]:
# Count number of devices
torch.cuda.device_count()

1

### 3. Putting tensors (and models) on GPU

The reson we want our tensors/models on the GPU results in faster computations

In [ ]:
# Create a tensor (default on the CPU)
tensor = torch.tensor ([1, 2, 3], device="cpu")

#Tensor not on GPU
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [ ]:
# Create a tensor (default on the CPU)
tensor = torch.tensor ([1, 2, 3])

#Tensor not on GPU
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [ ]:
# Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

### 4. Moving tensors back to the CPU

If tensor is on GPU, can't trasform it to NumPy

In [ ]:
# Error
tensor_on_gpu.numpy()

TypeError: ignored

In [ ]:
# To fix the GPU tensor with NumpPy issue, we can first set it to the CPU
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

In [ ]:
## Exercises & Extra-curriculum

link: https://www.learnpytorch.io/00_pytorch_fundamentals/#exercises